targets:
  $default:
    sources:
      - $package$
      - lib/**
    builders:
      json_serializable:
        generate_for:
          exclude:
            - lib/common/pagination/item_patch.dart
        options:
          field_rename: snake
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - "type=lint"
