coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 2%
    patch:
      default:
        target: 80%
        threshold: 5%

  ignore:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.config.dart"
    - "**/generated/**"
    - "**/l10n/**"
    - "lib/generated_plugin_registrant.dart"
    - "packages/**/test/**"
    - "dependencies/**"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

github_checks:
  annotations: true
